# BÀI 1: LÀM QUEN VỚI PYTORCH

## 1.Mục tiêu

• Sau khi hoàn thành bài thực hành, sinh viên có thể:

• Tạo, kiểm tra và thao tác với Tensor trong PyTorch.

• Thực hiện indexing, slicing, reshape và các phép toán ma trận trên Tensor.

• Sử dụng các hàm thống kê cơ bản trên Tensor.

• Hiểu cơ chế automatic differentiation (autograd) và vai trò của gradient.

• Sử dụng optimizer để giải bài toán tối ưu đơn giản bằng Gradient Descent.

• PyTorch cung cấp hai khả năng nền tảng: tính toán Tensor (tương tự NumPy, có thể tăng tốc bằng GPU) và
automatic differentiation để huấn luyện mô hình.


## 2.Bài tập thực hành

### Bài 1. Tạo Tensor cơ bản

Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [1]:
!pip install torch

In [5]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)
print("Kích thước:", a.shape)
print("Số chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32


### Bài 2. Tạo các Tensor thường dùng

Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [6]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.8923, 0.4364, 0.2868, 0.2872],
        [0.1396, 0.4909, 0.2068, 0.9215],
        [0.1531, 0.7590, 0.3242, 0.6780]])
tensor([[-0.6148, -0.2828,  1.9088, -0.9288],
        [-0.0312, -0.8747, -2.0068, -0.3176],
        [ 1.0885,  0.5201,  0.1688,  0.6915]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [7]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print("a (rand):\n", a)
print("b (randn):\n", b)
print("c (zeros):\n", c)
print("d (ones):\n", d)
print("e (eye):\n", e)

# Yêu cầu 2
f = torch.full((5, 5), 10)
print("\nTensor 5x5 toàn số 10:\n", f)

a (rand):
 tensor([[0.6990, 0.7400, 0.6309, 0.0166],
        [0.2283, 0.4750, 0.2973, 0.6421],
        [0.2661, 0.2811, 0.9754, 0.3584]])
b (randn):
 tensor([[-1.2632,  1.3013,  2.8613,  1.2794],
        [-0.9138, -1.3733, -0.1121, -0.4587],
        [-1.1063, -1.1380,  0.5219, -0.8689]])
c (zeros):
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
d (ones):
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
e (eye):
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Tensor 5x5 toàn số 10:
 tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### Bài 3. Kiểm tra thông tin Tensor

Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [9]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)


Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### Bài 4. Slicing và Indexing

Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [2]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.5850,  0.9874, -0.4416,  2.2120,  0.9272],
         [-1.0635,  0.6481, -0.2540,  1.0473,  0.6590],
         [-0.6266, -1.5269,  1.5627, -1.0155, -1.4978],
         [ 1.3025,  1.1317,  0.9778, -1.7131,  0.8863]],

        [[-1.2167, -1.0615, -0.8428,  1.2565,  1.4376],
         [-0.6378, -0.5250,  0.6434, -0.2723, -1.4780],
         [-2.2346, -1.6098, -0.2268,  0.4347,  0.5948],
         [ 0.5427, -0.5316,  1.3698,  1.5023, -0.1589]],

        [[ 1.0879,  1.5753, -1.0932,  0.3239,  0.1243],
         [ 0.2230, -1.4359,  1.7635,  2.3478,  0.8181],
         [ 1.4154, -1.0334, -0.6749, -0.2929, -0.5764],
         [-0.7674, -0.3688,  2.1435,  1.1715, -1.4272]]])

Tensor a[1]:
tensor([[-1.2167, -1.0615, -0.8428,  1.2565,  1.4376],
        [-0.6378, -0.5250,  0.6434, -0.2723, -1.4780],
        [-2.2346, -1.6098, -0.2268,  0.4347,  0.5948],
        [ 0.5427, -0.5316,  1.3698,  1.5023, -0.1589]])

Tensor a[1:, 2:4]:
tensor([[[-2.2346, -1.6098, -0.2268,  0.4347,  0.5

In [3]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

print("\nYÊU CẦU")
print("Shape của a[1]:", a[1].shape)
print("Shape của a[1:, 2:4]:", a[1:, 2:4].shape)
phan_tu_cuoi = a[:, :, -2:]
print("\nHai phần tử cuối cùng trên chiều thứ ba:\n", phan_tu_cuoi)

Original tensor:
tensor([[[-1.7018,  2.0275,  1.5334,  0.7607,  0.2607],
         [ 0.6310, -0.1919,  0.3433,  0.3936,  1.0759],
         [-0.6451,  0.9956, -1.6735, -0.2776,  0.6684],
         [-1.3478,  0.8779, -0.8129,  1.9517, -1.1472]],

        [[-1.1903,  1.9426,  0.1535,  1.1528,  1.0102],
         [ 1.0982,  0.8576,  0.0597,  0.4949, -0.3691],
         [-1.4458, -0.4452, -0.7553, -0.8801, -0.9141],
         [-1.4610,  0.8868, -1.3234,  0.5753, -0.4957]],

        [[ 0.1295, -1.4249,  1.1284, -0.4046, -0.5374],
         [ 0.1513, -0.6859,  1.7036, -2.4695, -1.3130],
         [ 0.0984,  0.6621, -0.8186, -0.9566, -1.1138],
         [ 1.4465,  0.1578, -1.1462,  0.4447, -0.2839]]])

Tensor a[1]:
tensor([[-1.1903,  1.9426,  0.1535,  1.1528,  1.0102],
        [ 1.0982,  0.8576,  0.0597,  0.4949, -0.3691],
        [-1.4458, -0.4452, -0.7553, -0.8801, -0.9141],
        [-1.4610,  0.8868, -1.3234,  0.5753, -0.4957]])

Tensor a[1:, 2:4]:
tensor([[[-1.4458, -0.4452, -0.7553, -0.8801, -0.9

### Bài 5. Reshape và Flatten

Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [5]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
b = a.reshape(3, 2, 2)
print("\nReshape to 3 x 2 x 2:")
print(b)


print("\nYÊU CẦU")
print("Số phần tử trước khi reshape (3x4):", a.numel())
print("Số phần tử sau khi reshape (3x2x2):", b.numel())

c = a.reshape(2, 6)
print("\nReshape Tensor thành 2 x 6:\n", c)

Original:
tensor([[ 0.2913,  1.8007,  0.3722,  0.8130],
        [ 2.0670,  0.5994,  0.2849,  0.7960],
        [-0.3981, -0.4853, -0.3503,  0.4228]])

Flatten:
tensor([ 0.2913,  1.8007,  0.3722,  0.8130,  2.0670,  0.5994,  0.2849,  0.7960,
        -0.3981, -0.4853, -0.3503,  0.4228])

Reshape to 3 x 2 x 2:
tensor([[[ 0.2913,  1.8007],
         [ 0.3722,  0.8130]],

        [[ 2.0670,  0.5994],
         [ 0.2849,  0.7960]],

        [[-0.3981, -0.4853],
         [-0.3503,  0.4228]]])

YÊU CẦU
Số phần tử trước khi reshape (3x4): 12
Số phần tử sau khi reshape (3x2x2): 12

Reshape Tensor thành 2 x 6:
 tensor([[ 0.2913,  1.8007,  0.3722,  0.8130,  2.0670,  0.5994],
        [ 0.2849,  0.7960, -0.3981, -0.4853, -0.3503,  0.4228]])


### Bài 6. Phép toán và nhân ma trận

Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [13]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:\n", a)
print("b:\n", b)
print("\na + b:\n", a + b)
print("\na / b:\n", a / b)
print("\na^2:\n", a ** 2)
print("\nMatrix multiplication (a @ b.T):\n", a @ b.T)

a:
 tensor([[-1.5054,  0.4757,  0.2877],
        [ 0.3766, -1.0250, -0.8007]])
b:
 tensor([[-0.7166, -0.2926, -0.6968],
        [ 0.4771, -1.2456, -0.3955]])

a + b:
 tensor([[-2.2220,  0.1831, -0.4091],
        [ 0.8536, -2.2706, -1.1963]])

a / b:
 tensor([[ 2.1008, -1.6257, -0.4129],
        [ 0.7893,  0.8229,  2.0243]])

a^2:
 tensor([[2.2662, 0.2263, 0.0828],
        [0.1418, 1.0507, 0.6411]])

Matrix multiplication (a @ b.T):
 tensor([[ 0.7391, -1.4245],
        [ 0.5880,  1.7731]])


In [15]:
print("\nYÊU CẦU")
print("Shape của a @ b.T:", (a @ b.T).shape)


YÊU CẦU
Shape của a @ b.T: torch.Size([2, 2])


### Bài 7. Các hàm thống kê trên Tensor

Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [11]:
import torch
a = torch.randn(3, 4)
print("a:\n", a)

print("Mean (dim=0):\n", torch.mean(a, dim=0))
print("Standard deviation (dim=0):\n", torch.std(a, dim=0))
print("Cumulative sum (dim=0):\n", torch.cumsum(a, dim=0))


a:
 tensor([[-1.3159,  0.0032, -0.6817, -0.6480],
        [-0.8282,  0.9857,  0.1208,  1.2373],
        [-0.0235,  0.0901,  0.1850, -0.3411]])
Mean (dim=0):
 tensor([-0.7225,  0.3597, -0.1253,  0.0827])
Standard deviation (dim=0):
 tensor([0.6526, 0.5439, 0.4829, 1.0116])
Cumulative sum (dim=0):
 tensor([[-1.3159,  0.0032, -0.6817, -0.6480],
        [-2.1440,  0.9889, -0.5609,  0.5893],
        [-2.1676,  1.0790, -0.3759,  0.2482]])


In [12]:
print("\nTinh theo Dim=1")
print("Mean (dim=1):\n", torch.mean(a, dim=1))
print("Standard deviation (dim=1):\n", torch.std(a, dim=1))
print("Cumulative sum (dim=1):\n", torch.cumsum(a, dim=1))


Tinh theo Dim=1
Mean (dim=1):
 tensor([-0.6606,  0.3789, -0.0224])
Standard deviation (dim=1):
 tensor([0.5387, 0.9361, 0.2290])
Cumulative sum (dim=1):
 tensor([[-1.3159, -1.3126, -1.9944, -2.6424],
        [-0.8282,  0.1575,  0.2784,  1.5157],
        [-0.0235,  0.0665,  0.2515, -0.0896]])


### Bài 8. Autograd cơ bản

Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [9]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [10]:
x2 = torch.tensor(3.6, requires_grad=True)
y2 = 3 * x2**2 + 2 * x2 + 1
y2.backward()
print("y =3*x^2+2*x +1")
print("x2 =", x2)
print("y2 =", y2)
print("x2.grad =", x2.grad)

y =3*x^2+2*x +1
x2 = tensor(3.6000, requires_grad=True)
y2 = tensor(47.0800, grad_fn=<AddBackward0>)
x2.grad = tensor(23.6000)


### Bài 9. Gradient Descent tìm hệ số đa thức

Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [18]:
import numpy as np
import torch

# Tạo dữ liệu mẫu
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

# Khởi tạo trọng số và dữ liệu PyTorch
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

# Vòng lặp huấn luyện
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("\nLearned coefficients:")
print(w)

Initial coefficients:
tensor([[-1.6457],
        [ 1.6900],
        [-0.3809]], requires_grad=True)

Learned coefficients:
tensor([[1.0091],
        [2.0002],
        [2.3482]], requires_grad=True)


### Bài 10. Giải hệ phương trình bằng Autograd

Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [21]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A.item())
print("B =", B.item())
print("C =", C.item())
print("D =", D.item())

A = 4.498263835906982
B = 4.501677513122559
C = 3.5017035007476807
D = 2.5016865730285645


In [22]:
print("\nKIỂM TRA NGHIỆM")
print(f"A + B = {A.item() + B.item():.4f} (Kỳ vọng: 9)")
print(f"C - D = {C.item() - D.item():.4f} (Kỳ vọng: 1)")
print(f"A + C = {A.item() + C.item():.4f} (Kỳ vọng: 8)")
print(f"B - D = {B.item() - D.item():.4f} (Kỳ vọng: 2)")


KIỂM TRA NGHIỆM
A + B = 8.9999 (Kỳ vọng: 9)
C - D = 1.0000 (Kỳ vọng: 1)
A + C = 8.0000 (Kỳ vọng: 8)
B - D = 2.0000 (Kỳ vọng: 2)


## 3. Bài tập áp dụng

### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:

• Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

• Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

• Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [26]:
import torch
torch.manual_seed(0)
print("PHẦN 1: Tensor X và các phép reshape")
 
# Tensor X có 24 phần tử (0..23)
X = torch.arange(24)
print("X ban đầu (1D, 24 phần tử):")
print(X)
 
X_4x6 = X.reshape(4, 6)
print("\nReshape thành 4x6:")
print(X_4x6)
 
X_2x12 = X.reshape(2, 12)
print("\nReshape thành 2x12:")
print(X_2x12)
 
X_2x3x4 = X.reshape(2, 3, 4)
print("\nReshape thành 2x3x4:")
print(X_2x3x4)

PHẦN 1: Tensor X và các phép reshape
X ban đầu (1D, 24 phần tử):
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Reshape thành 4x6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape thành 2x12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape thành 2x3x4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [27]:
print("PHẦN 2: Tensor A, B kích thước 3x4")
 
A = torch.randint(1, 10, (3, 4)).float()
B = torch.randint(1, 10, (3, 4)).float()
 
print("A =")
print(A)
print("\nB =")
print(B)
print("\nA + B =")
print(A + B)
print("\nA * B (element-wise) =")
print(A * B)
print("\nA / B (element-wise) =")
print(A / B)
# Trung bình và độ lệch chuẩn theo cột (dim=0 nghĩa là tính dọc theo từng cột)
mean_col_A = A.mean(dim=0)
std_col_A = A.std(dim=0)
mean_col_B = B.mean(dim=0)
std_col_B = B.std(dim=0)
print("\nTrung bình theo cột của A:", mean_col_A)
print("Độ lệch chuẩn theo cột của A:", std_col_A)
print("Trung bình theo cột của B:", mean_col_B)
print("Độ lệch chuẩn theo cột của B:", std_col_B)

PHẦN 2: Tensor A, B kích thước 3x4
A =
tensor([[9., 1., 3., 7.],
        [8., 7., 8., 2.],
        [2., 1., 9., 3.]])

B =
tensor([[7., 4., 2., 3.],
        [1., 1., 6., 4.],
        [9., 3., 9., 3.]])

A + B =
tensor([[16.,  5.,  5., 10.],
        [ 9.,  8., 14.,  6.],
        [11.,  4., 18.,  6.]])

A * B (element-wise) =
tensor([[63.,  4.,  6., 21.],
        [ 8.,  7., 48.,  8.],
        [18.,  3., 81.,  9.]])

A / B (element-wise) =
tensor([[1.2857, 0.2500, 1.5000, 2.3333],
        [8.0000, 7.0000, 1.3333, 0.5000],
        [0.2222, 0.3333, 1.0000, 1.0000]])

Trung bình theo cột của A: tensor([6.3333, 3.0000, 6.6667, 4.0000])
Độ lệch chuẩn theo cột của A: tensor([3.7859, 3.4641, 3.2146, 2.6458])
Trung bình theo cột của B: tensor([5.6667, 2.6667, 5.6667, 3.3333])
Độ lệch chuẩn theo cột của B: tensor([4.1633, 1.5275, 3.5119, 0.5774])


In [30]:
print("PHẦN 3: Autograd - đạo hàm y = 2x^2 + 5x + 3 tại x = 2")
 
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()
 
dy_dx_autograd = x.grad.item()
# Đạo hàm thủ công: dy/dx = 4x + 5  => tại x = 2: 4*2 + 5 = 13
dy_dx_manual = 4 * 2 + 5
 
print(f"y = 2x^2 + 5x + 3 tại x = 2 -> y = {y.item()}")
print(f"dy/dx (autograd) tại x = 2  = {dy_dx_autograd}")
print(f"dy/dx (tính tay: 4x + 5)    = {dy_dx_manual}")
print("Khớp nhau!" if abs(dy_dx_autograd - dy_dx_manual) < 1e-6 else "Không khớp!")

PHẦN 3: Autograd - đạo hàm y = 2x^2 + 5x + 3 tại x = 2
y = 2x^2 + 5x + 3 tại x = 2 -> y = 21.0
dy/dx (autograd) tại x = 2  = 13.0
dy/dx (tính tay: 4x + 5)    = 13
Khớp nhau!


In [32]:
print("PHẦN 4: Thay đa thức Bài 9 bằng y = 2x^2 - 3x + 5")
 
import numpy as np
 
# Tạo dữ liệu mẫu theo đa thức y = 2x^2 - 3x + 5
polynomial = np.poly1d([2, -3, 5])
N = 20
X_np = np.random.randn(N, 1) * 5
Y_np = polynomial(X_np)
 
XX = np.hstack([
    X_np * X_np,
    X_np,
    np.ones_like(X_np)
])
 
# Khởi tạo trọng số và dữ liệu PyTorch
w4 = torch.randn(3, 1, requires_grad=True)
x4 = torch.tensor(XX, dtype=torch.float32)
y4 = torch.tensor(Y_np, dtype=torch.float32)
optimizer4 = torch.optim.NAdam([w4], lr=0.01)
 
print("Hệ số khởi tạo (initial coefficients):")
print(w4)
 
# Vòng lặp huấn luyện
for epoch in range(1000):
    optimizer4.zero_grad()
    y_pred4 = x4 @ w4
    mse4 = torch.mean(torch.square(y4 - y_pred4))
    mse4.backward()
    optimizer4.step()
 
print("\nHệ số học được (learned coefficients):")
print(w4)
 
a_hat, b_hat, c_hat = w4.detach().squeeze().tolist()
print("\nKết quả:")
print(f"Đa thức thật     : y = 2x^2 - 3x + 5")
print(f"Đa thức học được : y = {a_hat:.3f}x^2 + {b_hat:.3f}x + {c_hat:.3f}")

PHẦN 4: Thay đa thức Bài 9 bằng y = 2x^2 - 3x + 5
Hệ số khởi tạo (initial coefficients):
tensor([[ 0.3956],
        [ 0.0895],
        [-0.1682]], requires_grad=True)

Hệ số học được (learned coefficients):
tensor([[ 2.0642],
        [-3.0489],
        [ 2.6040]], requires_grad=True)

Kết quả:
Đa thức thật     : y = 2x^2 - 3x + 5
Đa thức học được : y = 2.064x^2 + -3.049x + 2.604
